### PR TITLE
refactor: refactor callback with maa_types

### PR DESCRIPTION
**Pull request by KevinT3Hu**
This is still heavily a WIP since the crate maa_types(which was written merely according to the outdated docs) still lacks many items. 

I wish to get some help with that since I'm really familiar with the callback protocols present only in source code and not in docs.

### CODE REVIEW

**Comment by wangl-cc** [comment]
Thank you for your pull request. I've had a chance to review your `maa_types` library, and it appears that you've created some `serde` objects to represent tasks and messages. I've also experimented with a similar approach to simplify JSON parsing.

However, I have reservations about applying this approach to tasks, as it could potentially lead to blocking user input if `MaaCore` introduces new tasks or parameters that are not yet supported by this CLI. Unless we can establish a mechanism for deserializing and re-serializing undefined variants in enums and undefined fields in structs, this may not be a suitable solution for tasks.

In my opinion, this approach could be more feasible for messages, as it is unrelated to user input. Nevertheless, one challenge we might encounter is how to effectively handle missing messages during debugging.

Regarding callback protocols, I admit that I'm not very familiar with them. Most of the callbacks are based on the [implementation of the Windows GUI](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/8de6799bddfdb0a656dcaac4dd431cb79097d4b6/src/MaaWpfGui/Main/AsstProxy.cs#L366-L1177). To gather details about messages, my current approach involves modifying the callback and print messages from `MaaCore`.

I'm willing to assist in enhancing this pull request, but my availability is limited until next weekend (Sept 23). Please feel free to share any additional details about your concerns or issues here or in QQ (you can find me in developer group).

**Comment by wangl-cc** [comment]
By the way, would you be open to including your `maa_types` library as a part of the repository? This could be beneficial as the message processing is likely to have a strong dependency on it.

**Comment by KevinT3Hu** [comment]
I have merged the message part into the workspace of this crate and remove the dependency for the crate published to crates.io in the latest commit.

**Comment by wangl-cc** [comment]
Thank you. I've delved further into the callbacks of `MaaCore`, and it appears that most of the details about callback messages can be found in `src/MaaCore/Task`. Additionally, you can locate the subtask names (`subtask` field of subtask start messages) in `resource/tasks.json`.

<details>
<summary>Search results about SubTaskExtraInfo</summary>

Screenshot 2023-09-14 at 23 58 53

</details>

By the way, I've also search about capturing undefined fields in structs and undefined variants in enums. For structs, we can employ `#[serde(flatten)]` to capture them, as shown in the following example
```rust
#[derive(Serialize, Deserialize)]
struct S {
    a: u32,
    b: String,
    #[serde(flatten)]
    other: Map<String, Value>,
}
```
As for handling undefined variants in enums, although there isn't an official solution, there is a crate called [serde-enum-str](https://docs.rs/serde-enum-str/latest/serde_enum_str) that might be helpful.

**Comment by KevinT3Hu** [comment]
That would be helpful. I will look into these in the coming weekend.

**Pull request closed without merging**
